######################## default configuration ####################
baseURL = "https://atomtobyte.netlify.app/"
title = "Atom To Byte"
theme = "atomtobyte"
languageName = "En"
languageCode = "en-us"
# post pagination
paginate = "3"
# post excerpt
summaryLength = "15"
# disqus short name
disqusShortname = "" # get your shortname form here : https://disqus.com
# google analytics
googleAnalytics = "" # example : UA-123-45
# unsafe html
handle = "Home"
[markup.goldmark.renderer]
unsafe = true

############################# Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/extra.css"
[[params.plugins.css]]
link = "plugins/aos.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/aos.js"
[[params.plugins.js]]
link = "plugins/init.js"


############################## navigation ###############################

# main menu
[[menu.main]]
name = "Home"
URL = ""
weight = 1

[[menu.main]]
name = "Events"
URL = "events"
weight = 2

[[menu.main]]
name = "Members"
URL = "members"
weight = 3

[[menu.main]]
name = "Contact"
URL = "contact"
weight = 4

[[menu.main]]
name = "New"
URL = "new"
weight = 5


# Support 
[[menu.support]]
name = "Home"
URL = ""
weight = 1

[[menu.support]]
name = "Events"
URL = "events"
weight = 2

[[menu.support]]
name = "Members"
URL = "members"
weight = 3

[[menu.support]]
name = "Contact"
URL = "contact"
weight = 4

[[menu.support]]
name = "New"
URL = "new"
weight = 5

#################### default parameters ################################
[params]
logo = "images/logo.png"
logo_width = "200px"
# Meta data
description = "This is meta description"
author = "Prichoms"
# contact form action
contact_form_action = "https://submit-form.com/Lw1kvbWf"

########### footer content ##########
# copyright
copyright = ""

#Preloader
[params.preloader]
enable = true
preloader = "images/icon.png" # use jpg, png, svg or gif format...

# Navigation buttons
[params.navigation_button]
enable = true
label = "Get Started"
link = "contact"

  
############################# social site ########################

[[params.social]]
title = "youtube"
icon = "ti-youtube" # themify icon : https://themify.me/themify-icons
link = "https://youtube.com/channel/UCkpKr0tEQg9xGNmtYgpJUGg"

[[params.social]]
title = "instagram"
icon = "ti-instagram" # themify icon : https://themify.me/themify-icons
link = "https://instagram.com/atomtobyte"

[[params.social]]
title = "linkedin"
icon = "ti-linkedin" # themify icon : https://themify.me/themify-icons
link = "https://www.linkedin.com/company/atom-to-byte"

[[params.social]]
title = "twitter"
icon = "ti-twitter" # themify icon : https://themify.me/themify-icons
link = "https://twitter.com/atomtobyte"
